name: Commit new Swagger files to exo_documentation
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron:  '0 18 * * *' # Everyday at 6PM (before CI/CD)
jobs:
  get_and_commit_swagger_export_files:
    runs-on: ubuntu-latest
    env:
      TARGET_FOLDER: "docs/_static"
      SERVER_URL: "https://repository.exoplatform.org"
      PREFIX: "service/local/artifact/maven/redirect?"
      url:
           r=exo-snapshots&g=org.exoplatform.commons&a=commons-component-common&v=6.4.x-SNAPSHOT&c=swagger&e=json
           r=exo-snapshots&g=org.exoplatform.social&a=social-component-service&v=6.4.x-SNAPSHOT&c=swagger&e=json
           r=exo-snapshots&g=org.exoplatform.gatein.portal&a=exo.portal.component.portal&v=6.4.x-SNAPSHOT&c=swagger&e=json
           r=exo-snapshots&g=org.exoplatform.ecms&a=ecms-core-services&v=6.4.x-SNAPSHOT&c=swagger&e=json
           r=exo-addons-snapshots&g=org.exoplatform.addons.dlp&a=dlp-services&v=1.0.x-SNAPSHOT&c=swagger&e=json
           r=exo-addons-snapshots&g=org.exoplatform.anti-malware&a=anti-malware-services&v=1.0.x-SNAPSHOT&c=swagger&e=json
           r=exo-addons-snapshots&g=org.exoplatform.addons.app-center&a=app-center-services&v=2.4.x-SNAPSHOT&c=swagger&e=json
           r=exo-addons-snapshots&g=org.exoplatform.addons.kudos&a=kudos-services&v=2.4.x-SNAPSHOT&c=swagger&e=json
           r=exo-addons-snapshots&g=org.exoplatform.addons.multifactor-authentication&a=multifactor-authentication-services&v=1.2.x-SNAPSHOT&c=swagger&e=json
           r=exo-addons-snapshots&g=org.exoplatform.addons.web-conferencing&a=web-conferencing-services&v=2.4.x-SNAPSHOT&c=swagger&e=json
           r=exo-addons-snapshots&g=org.exoplatform.addons.onlyoffice&a=exo-onlyoffice-editor-services&v=2.4.x-SNAPSHOT&c=swagger&e=json
           r=exo-addons-snapshots&g=org.exoplatform.addons.chat&a=chat-services&v=3.4.x-SNAPSHOT&c=swagger&e=json
           r=exo-addons-snapshots&g=org.exoplatform.addons.poll&a=poll-services&v=1.1.x-SNAPSHOT&c=swagger&e=json
           r=exo-addons-snapshots&g=org.exoplatform.addons.perk-store&a=perk-store-services&v=2.4.x-SNAPSHOT&c=swagger&e=json
           r=exo-addons-snapshots&g=org.exoplatform.addons.notes&a=notes-service&v=1.2.x-SNAPSHOT&c=swagger&e=json
           r=exo-addons-snapshots&g=org.exoplatform.addons.task&a=task-management-services&v=3.4.x-SNAPSHOT&c=swagger&e=json
           r=exo-addons-snapshots&g=org.exoplatform.addons.wallet&a=wallet-api&v=2.4.x-SNAPSHOT&c=swagger&e=json
           r=exo-addons-snapshots&g=org.exoplatform.addons.gamification&a=gamification-services&v=2.4.x-SNAPSHOT&c=swagger&e=json
           r=exo-addons-snapshots&g=org.exoplatform.processes&a=processes-services&v=1.1.x-SNAPSHOT&c=swagger&e=json
           r=exo-snapshots&g=org.exoplatform.documents&a=documents-services&v=1.1.x-SNAPSHOT&c=swagger&e=json
           r=exo-snapshots&g=org.exoplatform.agenda&a=agenda-services&v=1.3.x-SNAPSHOT&c=swagger&e=json
           r=exo-addons-snapshots&g=org.exoplatform.addons.news&a=news-services&v=2.4.x-SNAPSHOT&c=swagger
    steps:
      # Check-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Download nexus metadata
        run: |
         cd $TARGET_FOLDER
         mkdir -p swagger
         pushd swagger
         for item in ${url}
         do
          file_name=$(echo ${item} | grep -o -P '(?<=m.).*(?=&a)')
          final_name=${file_name//./_}
         STATUSCODE=$(curl -s -L ${SERVER_URL}/${PREFIX}${item} --write-out '%{http_code}' --output ${final_name}_swagger.json)
         if test $STATUSCODE -ne 200; then
           echo "ERROR: ${final_name}_swagger.json : download Error. Status code : ${STATUSCODE}"
           echo ${SERVER_URL}/${PREFIX}${item} 
           echo "No files downloaded : nothing to commit"
           exit 1
         else
           echo "${final_name}_swagger.json download OK"
         fi
         done
         cd $GITHUB_WORKSPACE
           git status
           git config --global user.email "exo-swf@exoplatform.com"
           git config --global user.name "eXo Software Factory"
           git add -A
           git diff-index --quiet HEAD || git commit -m "Automated swagger exports commit"
           git push
