name: Commit new Swagger files to exo_documentation
on:
- push

jobs:
  get_and_commit_kb_export_files:
    runs-on: ubuntu-latest
    env:
      SERVER_URL: "https://repository.exoplatform.org"
      PREFIX: "content/repositories/public/org/exoplatform"
#       URLS_OF_FILES:
#           - "commons/commons-component-common/6.4.x-devx-SNAPSHOT/commons-component-common-6.4.x-devx-${TIMESTAMP}-${BUILD_NUMBER}-swagger.json"           #commons
#           - "social/social-component-service/6.4.x-devx-SNAPSHOT"                                                                                    #social
#           - "gatein/portal/exo.portal.component.portal/6.4.x-devx-SNAPSHOT"                                                                          #gatein_portal
#           - "ecms/ecms-core-services/6.4.x-devx-SNAPSHOT"                                                                                            #ecms
#           - "addons/dlp/dlp-services/1.0.x-devx-SNAPSHOT"                                                                                            #dlp_addon
#           - "anti-malware/anti-malware-services/1.0.x-devx-SNAPSHOT"                                                                                 #anti-malware
      MAVEN_METADATA: "maven-metadata.xml"

    steps:
      - name: Download nexus metadata
        run: |
          url=${SERVER_URL}/${PREFIX}/commons/commons-component-common/6.4.x-devx-SNAPSHOT/${MAVEN_METADATA}
          curl  -s $url | cat > commons-metadata.txt
          cat commons-metadata.txt
          TIMESTAMP=$((awk '/<timestamp>/ {print $1}'  commons-metadata.txt) | tr -dc '0-9''.')
          BUILD_NUMBER=$((awk '/<buildNumber>/ {print $1}'  commons-metadata.txt) | tr -dc '0-9''.')
          curl -u nexus:Nexus@eXo2020 -s ${SERVER_URL}/${PREFIX}/social/6.4.x-devx-SNAPSHOT/commons/commons-component-common/6.4.x-devx-SNAPSHOT/commons-component-common-6.4.x-devx-${TIMESTAMP}-${BUILD_NUMBER}-swagger.json > swagger_common.json
          cat swagger_common.json
