name: test
on:
- push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      url: 
           r=exo-snapshots&g=org.exoplatform.commons&a=commons-component-common&v=6.4.x-devx-SNAPSHOT&c=swagger&e=json
           r=exo-snapshots&g=org.exoplatform.social&a=social-component-service&v=6.4.x-devx-SNAPSHOT&c=swagger&e=json
           r=exo-snapshots&g=org.exoplatform.gatein.portal&a=exo.portal.component.portal&v=6.4.x-devx-SNAPSHOT&c=swagger&e=json
           r=exo-snapshots&g=org.exoplatform.ecms&a=ecms-core-services&v=6.4.x-devx-SNAPSHOT&c=swagger&e=json
           r=exo-addons-snapshots&g=org.exoplatform.addons.dlp&a=dlp-services&v=1.0.x-devx-SNAPSHOT&c=swagger&e=json
           r=exo-addons-snapshots&g=org.exoplatform.anti-malware&a=anti-malware-services&v=1.0.x-devx-SNAPSHOT&c=swagger&e=json
          
    steps:
      - name: test
        run: |
         echo "this is my ${url}" 
         for item in ${url}
         do
         echo `expr index "$item" =`
         done
         echo "done !!!!" 